"""add_messaging_and_reporting

Revision ID: 5b216dedeaf9
Revises: a8617967f942
Create Date: 2026-07-21 19:40:19.214083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.user
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5b216dedeaf9'
down_revision: Union[str, None] = 'a8617967f942'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('message_type', sa.Enum('TEXT', 'IMAGE', 'LOCATION', name='messagetype'), nullable=False),
    sa.Column('content', sa.String(length=2000), nullable=True),
    sa.Column('media_url', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.String(length=30), nullable=True),
    sa.Column('longitude', sa.String(length=30), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_messages_booking_id'), 'booking_messages', ['booking_id'], unique=False)
    op.create_table('booking_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_number', sa.String(length=50), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('against_user_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.Enum('SAFETY', 'BEHAVIOR', 'LATE_ARRIVAL', 'WRONG_ROUTE', 'FARE_ISSUE', 'PAYMENT_ISSUE', 'HARASSMENT', 'EMERGENCY', 'VEHICLE_ISSUE', 'LOST_ITEM', 'TECHNICAL_PROBLEM', 'OTHER', name='reportcategory'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='reportseverity'), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'WAITING_RESPONSE', 'RESOLVED', 'CLOSED', 'REJECTED', name='reportstatus'), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('assigned_admin_id', sa.Integer(), nullable=True),
    sa.Column('resolution_notes', sa.String(length=1000), nullable=True),
    sa.Column('resolution_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['against_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_reports_booking_id'), 'booking_reports', ['booking_id'], unique=False)
    op.create_index(op.f('ix_booking_reports_report_number'), 'booking_reports', ['report_number'], unique=True)
    op.alter_column('assistant_profiles', 'aadhaar_number_enc',
               existing_type=mysql.TINYBLOB(),
               type_=sa.LargeBinary(length=255),
               existing_nullable=True)
    op.create_foreign_key(None, 'bookings', 'payments', ['payment_id'], ['id'], ondelete='SET NULL')
    op.drop_column('bookings', 'discount_amount')
    op.alter_column('invoices', 'status',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('GENERATING', 'GENERATED', 'FAILED', name='invoicestatus'),
               existing_nullable=False)
    op.drop_index(op.f('uq_invoice_number'), table_name='invoices')
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.alter_column('payments', 'payment_method',
               existing_type=mysql.ENUM('UPI', 'CARD', 'NETBANKING', 'WALLET'),
               type_=sa.Enum('ONLINE', 'CASH', 'UPI', 'CARD', 'NETBANKING', 'WALLET', name='paymentmethod'),
               existing_nullable=True)
    op.alter_column('payments', 'status',
               existing_type=mysql.ENUM('CREATED', 'AUTHORIZED', 'CAPTURED', 'FAILED', 'REFUNDED'),
               type_=sa.Enum('NOT_STARTED', 'ORDER_CREATED', 'PAYMENT_PENDING', 'AUTHORIZED', 'CAPTURED', 'COMPLETED', 'FAILED', 'CANCELLED', 'REFUNDED', name='paymentstatus'),
               existing_nullable=False)
    op.create_unique_constraint(None, 'payments', ['idempotency_key'])
    op.create_unique_constraint(None, 'payments', ['payment_reference'])
    op.alter_column('payout_accounts', 'account_number_enc',
               existing_type=mysql.TINYBLOB(),
               type_=sa.LargeBinary(length=255),
               existing_nullable=False)
    op.alter_column('users', 'profile_photo_url',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(),
               existing_nullable=True)
    op.add_column('wallet_transactions', sa.Column('idempotency_key', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'wallet_transactions', ['idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallet_transactions', type_='unique')
    op.drop_column('wallet_transactions', 'idempotency_key')
    op.alter_column('users', 'profile_photo_url',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.alter_column('payout_accounts', 'account_number_enc',
               existing_type=sa.LargeBinary(length=255),
               type_=mysql.TINYBLOB(),
               existing_nullable=False)
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_constraint(None, 'payments', type_='unique')
    op.alter_column('payments', 'status',
               existing_type=sa.Enum('NOT_STARTED', 'ORDER_CREATED', 'PAYMENT_PENDING', 'AUTHORIZED', 'CAPTURED', 'COMPLETED', 'FAILED', 'CANCELLED', 'REFUNDED', name='paymentstatus'),
               type_=mysql.ENUM('CREATED', 'AUTHORIZED', 'CAPTURED', 'FAILED', 'REFUNDED'),
               existing_nullable=False)
    op.alter_column('payments', 'payment_method',
               existing_type=sa.Enum('ONLINE', 'CASH', 'UPI', 'CARD', 'NETBANKING', 'WALLET', name='paymentmethod'),
               type_=mysql.ENUM('UPI', 'CARD', 'NETBANKING', 'WALLET'),
               existing_nullable=True)
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.create_index(op.f('uq_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.alter_column('invoices', 'status',
               existing_type=sa.Enum('GENERATING', 'GENERATED', 'FAILED', name='invoicestatus'),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
    op.add_column('bookings', sa.Column('discount_amount', mysql.DECIMAL(precision=10, scale=2), nullable=False))
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.alter_column('assistant_profiles', 'aadhaar_number_enc',
               existing_type=sa.LargeBinary(length=255),
               type_=mysql.TINYBLOB(),
               existing_nullable=True)
    op.drop_index(op.f('ix_booking_reports_report_number'), table_name='booking_reports')
    op.drop_index(op.f('ix_booking_reports_booking_id'), table_name='booking_reports')
    op.drop_table('booking_reports')
    op.drop_index(op.f('ix_booking_messages_booking_id'), table_name='booking_messages')
    op.drop_table('booking_messages')
    # ### end Alembic commands ###
