"""Initial migration

Revision ID: a8617967f942
Revises: None
Create Date: 2026-07-11 04:22:35.398467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.user


# revision identifiers, used by Alembic.
revision: str = 'a8617967f942'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('discount_type', sa.Enum('FLAT', 'PERCENTAGE', name='coupondiscounttype'), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('max_discount_amount', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('min_booking_amount', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('usage_limit_per_user', sa.Integer(), nullable=True),
    sa.Column('total_usage_limit', sa.Integer(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('faqs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('question', sa.String(length=255), nullable=False),
    sa.Column('answer', sa.String(length=2000), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fare_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_point_type', sa.Enum('RAILWAY_STATION', 'AIRPORT', 'BUS_STAND', 'GENERAL', name='servicepointtype'), nullable=False),
    sa.Column('base_fare', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('per_km_rate', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('per_min_rate', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('min_fare', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('surge_multiplier', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('otp_verifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('identifier', sa.String(length=150), nullable=False),
    sa.Column('otp_hash', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.Enum('SIGNUP', 'LOGIN', 'RESET_PASSWORD', name='otppurpose'), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_identifier_purpose', 'otp_verifications', ['identifier', 'purpose'], unique=False)
    op.create_index(op.f('ix_otp_verifications_identifier'), 'otp_verifications', ['identifier'], unique=False)
    op.create_table('service_points',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('type', sa.Enum('RAILWAY_STATION', 'AIRPORT', 'BUS_STAND', 'GENERAL', name='servicepointtype'), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('coordinates', app.models.user.MySQLPoint(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_service_point_coords', 'service_points', ['coordinates'], unique=False, mysql_prefix='SPATIAL')
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('user_type', sa.Enum('GUEST', 'ASSISTANT', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('profile_photo_url', sa.String(length=500), nullable=True),
    sa.Column('auth_provider', sa.Enum('LOCAL', 'GOOGLE', name='authprovider'), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('is_phone_verified', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'DELETED', name='userstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_index(op.f('ix_users_public_id'), 'users', ['public_id'], unique=True)
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('dark_mode', sa.Boolean(), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('assistant_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bio', sa.String(length=1000), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('aadhaar_number_enc', sa.LargeBinary(length=255), nullable=True),
    sa.Column('aadhaar_masked', sa.String(length=20), nullable=True),
    sa.Column('verification_status', sa.Enum('NOT_SUBMITTED', 'PENDING', 'VERIFIED', 'REJECTED', name='kycstatus'), nullable=False),
    sa.Column('kyc_reviewed_by', sa.Integer(), nullable=True),
    sa.Column('kyc_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trust_score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('avg_rating', sa.Numeric(precision=2, scale=1), nullable=False),
    sa.Column('total_trips', sa.Integer(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('current_location', app.models.user.MySQLPoint(), nullable=False),
    sa.Column('location_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('service_radius_km', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['kyc_reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_assistant_location', 'assistant_profiles', ['current_location'], unique=False, mysql_prefix='SPATIAL')
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_code', sa.String(length=20), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('assistant_id', sa.Integer(), nullable=True),
    sa.Column('pickup_service_point_id', sa.Integer(), nullable=True),
    sa.Column('pickup_address', sa.String(length=500), nullable=False),
    sa.Column('pickup_coordinates', app.models.user.MySQLPoint(), nullable=False),
    sa.Column('destination_address', sa.String(length=500), nullable=False),
    sa.Column('destination_coordinates', app.models.user.MySQLPoint(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SEARCHING', 'ASSIGNED', 'ASSISTANT_ENROUTE', 'ARRIVED_PICKUP', 'GUEST_PICKED_UP', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='bookingstatus'), nullable=False),
    sa.Column('distance_km', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('estimated_duration_min', sa.Integer(), nullable=True),
    sa.Column('fare_estimate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('final_fare', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('coupon_id', sa.Integer(), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cancellation_reason', sa.String(length=255), nullable=True),
    sa.Column('cancelled_by', sa.Enum('GUEST', 'ASSISTANT', 'ADMIN', 'SYSTEM', name='cancelledby'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assistant_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['guest_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pickup_service_point_id'], ['service_points.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_booking_assistant_status', 'bookings', ['assistant_id', 'status'], unique=False)
    op.create_index('idx_booking_dest_location', 'bookings', ['destination_coordinates'], unique=False, mysql_prefix='SPATIAL')
    op.create_index('idx_booking_guest_status', 'bookings', ['guest_id', 'status'], unique=False)
    op.create_index('idx_booking_pickup_location', 'bookings', ['pickup_coordinates'], unique=False, mysql_prefix='SPATIAL')
    op.create_index(op.f('ix_bookings_booking_code'), 'bookings', ['booking_code'], unique=True)
    op.create_table('device_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fcm_token', sa.String(length=500), nullable=False),
    sa.Column('device_type', sa.Enum('ANDROID', 'IOS', 'WEB', name='devicetype'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_user_fcm', 'device_tokens', ['user_id', 'fcm_token'], unique=True)
    op.create_table('emergency_contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('relationship', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=False),
    sa.Column('type', sa.Enum('BOOKING', 'PAYMENT', 'PROMO', 'SYSTEM', 'SAFETY', name='notificationtype'), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('device_info', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.Enum('HOME', 'OFFICE', 'FAVORITE', 'OTHER', name='locationlabel'), nullable=False),
    sa.Column('custom_label', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('coordinates', app.models.user.MySQLPoint(), nullable=False),
    sa.Column('place_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_saved_coords', 'saved_locations', ['coordinates'], unique=False, mysql_prefix='SPATIAL')
    op.create_table('support_tickets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='ticketstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='ticketpriority'), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('assistant_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assistant_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assistant_id'], ['assistant_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking_status_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coupon_redemptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coupon_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    op.create_table('live_locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('coordinates', app.models.user.MySQLPoint(), nullable=False),
    sa.Column('heading', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_live_booking', 'live_locations', ['booking_id', 'recorded_at'], unique=False)
    op.create_index('idx_live_coordinates', 'live_locations', ['coordinates'], unique=False, mysql_prefix='SPATIAL')
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('payment_method', sa.Enum('UPI', 'CARD', 'NETBANKING', 'WALLET', name='paymentmethod'), nullable=True),
    sa.Column('gateway', sa.String(length=30), nullable=False),
    sa.Column('gateway_order_id', sa.String(length=100), nullable=True),
    sa.Column('gateway_payment_id', sa.String(length=100), nullable=True),
    sa.Column('gateway_signature', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'AUTHORIZED', 'CAPTURED', 'FAILED', 'REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gateway_order_id'),
    sa.UniqueConstraint('gateway_payment_id')
    )
    op.create_table('payout_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assistant_id', sa.Integer(), nullable=False),
    sa.Column('account_holder_name', sa.String(length=150), nullable=False),
    sa.Column('account_number_enc', sa.LargeBinary(length=255), nullable=False),
    sa.Column('ifsc_code', sa.String(length=11), nullable=True),
    sa.Column('upi_id', sa.String(length=100), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assistant_id'], ['assistant_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payouts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assistant_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='payoutstatus'), nullable=False),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('initiated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assistant_id'], ['assistant_profiles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ratings_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('rated_by', sa.Integer(), nullable=False),
    sa.Column('rated_assistant_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rated_assistant_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    op.create_table('sos_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('coordinates', app.models.user.MySQLPoint(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'RESOLVED', 'FALSE_ALARM', name='sosstatus'), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sos_coordinates', 'sos_alerts', ['coordinates'], unique=False, mysql_prefix='SPATIAL')
    op.create_table('support_ticket_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trip_shares',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('share_token', sa.CHAR(length=32), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_token')
    )
    op.create_table('wallet_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('CREDIT', 'DEBIT', name='wallettransactiontype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reference_type', sa.Enum('BOOKING', 'REFUND', 'TOPUP', 'PAYOUT', name='wallettransactionreftype'), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('balance_after', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet_transactions')
    op.drop_table('trip_shares')
    op.drop_table('support_ticket_messages')
    op.drop_index('idx_sos_coordinates', table_name='sos_alerts', mysql_prefix='SPATIAL')
    op.drop_table('sos_alerts')
    op.drop_table('ratings_reviews')
    op.drop_table('payouts')
    op.drop_table('payout_accounts')
    op.drop_table('payments')
    op.drop_index('idx_live_coordinates', table_name='live_locations', mysql_prefix='SPATIAL')
    op.drop_index('idx_live_booking', table_name='live_locations')
    op.drop_table('live_locations')
    op.drop_table('coupon_redemptions')
    op.drop_table('booking_status_history')
    op.drop_table('assistant_documents')
    op.drop_table('wallets')
    op.drop_table('support_tickets')
    op.drop_index('idx_saved_coords', table_name='saved_locations', mysql_prefix='SPATIAL')
    op.drop_table('saved_locations')
    op.drop_table('refresh_tokens')
    op.drop_table('notifications')
    op.drop_table('emergency_contacts')
    op.drop_index('uq_user_fcm', table_name='device_tokens')
    op.drop_table('device_tokens')
    op.drop_index(op.f('ix_bookings_booking_code'), table_name='bookings')
    op.drop_index('idx_booking_pickup_location', table_name='bookings', mysql_prefix='SPATIAL')
    op.drop_index('idx_booking_guest_status', table_name='bookings')
    op.drop_index('idx_booking_dest_location', table_name='bookings', mysql_prefix='SPATIAL')
    op.drop_index('idx_booking_assistant_status', table_name='bookings')
    op.drop_table('bookings')
    op.drop_table('audit_logs')
    op.drop_index('idx_assistant_location', table_name='assistant_profiles', mysql_prefix='SPATIAL')
    op.drop_table('assistant_profiles')
    op.drop_table('app_settings')
    op.drop_index(op.f('ix_users_public_id'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('idx_service_point_coords', table_name='service_points', mysql_prefix='SPATIAL')
    op.drop_table('service_points')
    op.drop_index(op.f('ix_otp_verifications_identifier'), table_name='otp_verifications')
    op.drop_index('idx_identifier_purpose', table_name='otp_verifications')
    op.drop_table('otp_verifications')
    op.drop_table('fare_rules')
    op.drop_table('faqs')
    op.drop_table('coupons')
    # ### end Alembic commands ###
